"""
Speculative Decoding Continuity Engine.

Implements the speculative decoding continuity mechanism described in
Section 3.4 of MorphCloud-LLM (Electronics 2026). During instance
migration, draft-model token generation is offloaded to on-demand
fallback nodes. Draft tokens are BUFFERED and NOT streamed to the user
until the target model is restored and retroactive verification completes.

Key specifications (Section 3.4 and Section 4.10):
  - Mean continuity window: 547 ms (SD 83 ms) across 521 events
  - p95: 698 ms; p99: 812 ms; max: 934 ms
  - LLaMA-70B: mean k=41.2 speculative tokens, acceptance rate=87.3%
  - Mixtral-8x7B: mean k=38.7 speculative tokens, acceptance rate=89.1%
  - ROUGE-L: 0.923 (LLaMA-70B), 0.941 (Mixtral-8x7B)
  - Rollback latency: 18.3 ms (LLaMA-70B), 14.6 ms (Mixtral-8x7B)
  - p99 latency overhead: 2.1% (rollback already included)

The transient distribution mismatch (exposure bias, Section 3.4 discussion)
is mitigated through short migration windows, high acceptance rates, and
retroactive verification by the restored target model.
"""

import logging
import math
import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import List, Optional, Tuple

import numpy as np
import torch

logger = logging.getLogger(__name__)


class ServingMode(Enum):
    """
    Equation 15: Mode(t) = Normal | Continuity.

    Normal     : Request being served on an active spot instance.
    Continuity : Draft model offloaded to fallback node during migration.
    """
    NORMAL = auto()
    CONTINUITY = auto()


@dataclass
class SpeculativeToken:
    """A single speculative token generated by the draft model M_d."""
    token_id: int
    log_prob_draft: float    # log P_{M_d}(x_i | x_{<i})
    log_prob_target: Optional[float] = None  # log P_{M_t}(x_i | x_{<i}), filled post-verification
    accepted: Optional[bool] = None          # None until verified
    position: int = 0                        # Absolute sequence position


@dataclass
class ContinuityWindowStats:
    """Statistics for a single continuity window (one migration event)."""
    session_id: str
    model_name: str
    event_id: int
    start_time_s: float
    end_time_s: float = 0.0
    n_speculative_tokens: int = 0
    n_rejected_tokens: int = 0
    rollback_position: int = 0
    n_regenerated_tokens: int = 0
    rollback_latency_ms: float = 0.0
    rouge_l: float = 0.0
    accepted: bool = True

    @property
    def duration_ms(self) -> float:
        return (self.end_time_s - self.start_time_s) * 1000

    @property
    def acceptance_rate(self) -> float:
        if self.n_speculative_tokens == 0:
            return 1.0
        return 1.0 - (self.n_rejected_tokens / self.n_speculative_tokens)


class SpeculativeDecodingContinuityEngine:
    """
    Speculative Decoding Continuity Engine.

    Normal operation (Mode = Normal):
      The draft model M_d runs on the same GPU as M_t and generates k candidate
      tokens. M_t verifies them in parallel (Equation 14).

    Continuity mode (Mode = Continuity, triggered when rho(t) > rho_thresh):
      1. Draft model M_d is offloaded to on-demand fallback node d_j.
      2. M_d generates tokens without immediate target-model verification.
      3. Draft tokens are BUFFERED — not streamed to the user.
      4. After M_t is restored on the replacement instance, retroactive
         verification is performed (Equation 16).
      5. Accepted tokens are flushed atomically; rejected tokens trigger
         rollback to the last verified position and regeneration.

    End-to-end latency overhead (Equation 18):
      delta_T_migration = T_recovery + k * t_verify - k * t_draft
    """

    def __init__(
        self,
        draft_model=None,
        target_model=None,
        fallback_node_url: str = "",
        max_draft_tokens: int = 64,
    ):
        self.draft_model = draft_model
        self.target_model = target_model
        self.fallback_node_url = fallback_node_url
        self.max_draft_tokens = max_draft_tokens

        self.current_mode = ServingMode.NORMAL
        self._token_buffer: List[SpeculativeToken] = []
        self._last_verified_position: int = 0
        self._context_ids: List[int] = []

        # Statistics across all migration events
        self._window_stats: List[ContinuityWindowStats] = []
        self._current_window: Optional[ContinuityWindowStats] = None

    # ------------------------------------------------------------------
    # Mode management
    # ------------------------------------------------------------------

    def enter_continuity_mode(self, session_id: str, model_name: str, event_id: int):
        """
        Switch to Continuity mode when preemption prediction triggers migration.
        Initializes a new continuity window statistics record.
        """
        if self.current_mode == ServingMode.CONTINUITY:
            return

        self.current_mode = ServingMode.CONTINUITY
        self._token_buffer = []
        self._current_window = ContinuityWindowStats(
            session_id=session_id,
            model_name=model_name,
            event_id=event_id,
            start_time_s=time.perf_counter(),
        )
        logger.info(
            "Entered continuity mode: session=%s event=%d", session_id, event_id
        )

    def exit_continuity_mode(self) -> Optional[ContinuityWindowStats]:
        """
        Switch back to Normal mode after target model is restored.
        Returns the statistics for the completed continuity window.
        """
        if self.current_mode == ServingMode.NORMAL:
            return None

        self.current_mode = ServingMode.NORMAL
        if self._current_window:
            self._current_window.end_time_s = time.perf_counter()
            self._window_stats.append(self._current_window)
            stats = self._current_window
            self._current_window = None
            logger.info(
                "Exited continuity mode: duration=%.1f ms k=%d acceptance=%.1f%%",
                stats.duration_ms,
                stats.n_speculative_tokens,
                stats.acceptance_rate * 100,
            )
            return stats
        return None

    # ------------------------------------------------------------------
    # Speculative token generation (continuity mode)
    # ------------------------------------------------------------------

    def generate_draft_tokens(
        self, context_ids: List[int], n_tokens: int
    ) -> List[SpeculativeToken]:
        """
        Generate n_tokens speculative tokens using the draft model M_d
        on the on-demand fallback node. Tokens are buffered, not returned
        to the user until retroactive verification completes.

        In continuity mode the draft model conditions on its own previous
        outputs, creating a transient distribution mismatch analogous to
        the exposure-bias problem in seq2seq learning (Section 3.4).
        This is mitigated by high acceptance rates and short migration windows.
        """
        if self.current_mode != ServingMode.CONTINUITY:
            raise RuntimeError("generate_draft_tokens called outside continuity mode.")
        if n_tokens <= 0:
            return []
        if n_tokens > self.max_draft_tokens:
            raise ValueError(
                f"n_tokens={n_tokens} exceeds max_draft_tokens={self.max_draft_tokens}"
            )

        draft_tokens: List[SpeculativeToken] = []
        current_context = list(context_ids)

        for i in range(n_tokens):
            token_id, log_prob = self._draft_forward(current_context)
            tok = SpeculativeToken(
                token_id=token_id,
                log_prob_draft=log_prob,
                position=self._last_verified_position + len(self._token_buffer) + i + 1,
            )
            draft_tokens.append(tok)
            current_context.append(token_id)

        self._token_buffer.extend(draft_tokens)
        if self._current_window:
            self._current_window.n_speculative_tokens += len(draft_tokens)

        logger.debug(
            "Generated %d draft tokens (buffer total: %d)",
            len(draft_tokens), len(self._token_buffer),
        )
        return draft_tokens

    def _draft_forward(self, context_ids: List[int]) -> Tuple[int, float]:
        """
        Run one forward pass of the draft model M_d.
        In production: call the remote fallback node serving endpoint.
        Returns (token_id, log_prob).
        """
        if self.draft_model is None:
            raise NotImplementedError(
                "Draft-model adapter is not included in the supplied artifact."
            )
        forward = getattr(self.draft_model, "next_token", None)
        if forward is None:
            raise NotImplementedError(
                "draft_model must expose next_token(context_ids) -> (token_id, log_prob)"
            )
        return forward(context_ids)

    # ------------------------------------------------------------------
    # Retroactive verification (Equations 14, 16, 17)
    # ------------------------------------------------------------------

    def verify_buffer(
        self, context_ids: List[int]
    ) -> Tuple[List[int], int, float]:
        """
        Retroactive verification of the speculative token buffer by the
        restored target model M_t (Equation 16).

        x_verified = Verify(M_t, x_speculative, x_context)

        Acceptance criterion (Equation 14):
          P_accept(x_i) = min(1, P_{M_t}(x_i | x_{<i}) / P_{M_d}(x_i | x_{<i}))

        Tokens rejected during verification trigger rollback to the last
        verified position; rejected tokens are regenerated by M_t before
        the response is flushed to the user.

        Returns
        -------
        accepted_ids : List[int]
            Final verified token ids to deliver to the user.
        n_rejected : int
            Number of tokens that failed verification and were regenerated.
        rollback_latency_ms : float
            Additional latency incurred by rollback and regeneration.
        """
        if not self._token_buffer:
            return [], 0, 0.0

        t0 = time.perf_counter()
        accepted_ids: List[int] = []
        rollback_position: int = -1
        n_rejected: int = 0

        for idx, tok in enumerate(self._token_buffer):
            target_log_prob = self._target_forward(context_ids + accepted_ids, tok.token_id)
            tok.log_prob_target = target_log_prob

            accept_prob = self._acceptance_probability(
                tok.log_prob_target, tok.log_prob_draft
            )
            u = np.random.uniform(0, 1)
            if u <= accept_prob:
                tok.accepted = True
                accepted_ids.append(tok.token_id)
            else:
                tok.accepted = False
                rollback_position = tok.position
                n_rejected = len(self._token_buffer) - idx
                break

        # Rollback and regenerate rejected tokens
        if n_rejected > 0:
            if self._current_window:
                self._current_window.rollback_position = rollback_position
                self._current_window.n_rejected_tokens += n_rejected
            # Regenerate from rollback position using M_t
            regenerated = self._regenerate_from_target(
                context_ids + accepted_ids, n_rejected
            )
            accepted_ids.extend(regenerated)
            if self._current_window:
                self._current_window.n_regenerated_tokens += len(regenerated)

        rollback_latency_ms = (time.perf_counter() - t0) * 1000
        if self._current_window and n_rejected > 0:
            self._current_window.rollback_latency_ms += rollback_latency_ms

        self._last_verified_position += len(accepted_ids)
        self._token_buffer = []

        logger.debug(
            "Verification: %d accepted / %d speculative, %d rejected, "
            "rollback latency=%.1f ms",
            len(accepted_ids) - n_rejected, len(self._token_buffer) + len(accepted_ids),
            n_rejected, rollback_latency_ms,
        )
        return accepted_ids, n_rejected, rollback_latency_ms

    def _acceptance_probability(
        self, log_prob_target: float, log_prob_draft: float
    ) -> float:
        """
        Equation 14: P_accept(x_i) = min(1, P_{M_t}(x_i) / P_{M_d}(x_i)).
        Computed in log space for numerical stability.
        """
        log_ratio = log_prob_target - log_prob_draft
        return min(1.0, math.exp(log_ratio))

    def _target_forward(self, context_ids: List[int], token_id: int) -> float:
        """Return log P_Mt(token_id | context_ids) from the target adapter."""
        if self.target_model is None:
            raise NotImplementedError(
                "Target-model verification adapter is not included in the supplied artifact."
            )
        score = getattr(self.target_model, "token_log_prob", None)
        if score is None:
            raise NotImplementedError(
                "target_model must expose token_log_prob(context_ids, token_id) for verification"
            )
        return float(score(context_ids, token_id))

    def _regenerate_from_target(
        self, context_ids: List[int], n_tokens: int
    ) -> List[int]:
        """
        Regenerate rejected tokens using the restored target model M_t.
        Adds mean rollback latency of 18.3 ms (LLaMA-70B) or 14.6 ms (Mixtral-8x7B).
        """
        if self.target_model is None:
            raise NotImplementedError(
                "Target-model regeneration adapter is not included in the supplied artifact."
            )
        generate = getattr(self.target_model, "generate_tokens", None)
        if generate is None:
            raise NotImplementedError(
                "target_model must expose generate_tokens(context_ids, n_tokens)"
            )
        return list(generate(context_ids, n_tokens))

    # ------------------------------------------------------------------
    # Expected resample count (Equation 17)
    # ------------------------------------------------------------------

    @staticmethod
    def expected_resamples(k: int, mean_acceptance_rate: float) -> float:
        """
        Equation 17: E[n_resample] = k * (1 - E[P_accept]).

        For LLaMA-70B:   k=41.2, P_accept=0.873 -> E[n_resample] = 5.2
        For Mixtral-8x7B: k=38.7, P_accept=0.891 -> E[n_resample] = 4.3
        """
        return k * (1.0 - mean_acceptance_rate)

    # ------------------------------------------------------------------
    # End-to-end migration latency overhead (Equation 18)
    # ------------------------------------------------------------------

    @staticmethod
    def migration_latency_overhead(
        t_recovery_ms: float,
        k: int,
        t_verify_ms: float,
        t_draft_ms: float,
    ) -> float:
        """
        Equation 18: delta_T_migration = T_recovery + k * t_verify - k * t_draft.
        """
        return t_recovery_ms + k * t_verify_ms - k * t_draft_ms

    # ------------------------------------------------------------------
    # Aggregate statistics
    # ------------------------------------------------------------------

    def aggregate_stats(self) -> dict:
        """
        Aggregate statistics across all completed continuity windows,
        matching the reported values in Sections 3.4 and 4.10.
        """
        if not self._window_stats:
            return {}

        durations = [w.duration_ms for w in self._window_stats]
        acceptance_rates = [w.acceptance_rate for w in self._window_stats]
        k_values = [w.n_speculative_tokens for w in self._window_stats]
        rollback_latencies = [w.rollback_latency_ms for w in self._window_stats
                               if w.n_rejected_tokens > 0]

        return {
            "n_events": len(self._window_stats),
            "continuity_window_mean_ms": float(np.mean(durations)),
            "continuity_window_sd_ms": float(np.std(durations)),
            "continuity_window_p95_ms": float(np.percentile(durations, 95)),
            "continuity_window_p99_ms": float(np.percentile(durations, 99)),
            "continuity_window_max_ms": float(np.max(durations)),
            "mean_acceptance_rate": float(np.mean(acceptance_rates)),
            "mean_k": float(np.mean(k_values)),
            "mean_rollback_latency_ms": float(np.mean(rollback_latencies)) if rollback_latencies else 0.0,
        }

